### ISSUE TITLE
where can i find the parsed_set.txt? or how to create it?

### ISSUE THREAD

**Issue by CATHUR** [epiception/CalibNet#2]

**Comment by epiception** [comment]
Hi!

parser.py in code/dataset_files/ creates the `parsed_set.txt` file

**Comment by CATHUR** [comment]
first,it works for me, thanks a lot. And i have another question.
how could i do if i want to run the train_model_combined.py using one gpu?

**Comment by epiception** [comment]
Unfortunately, due to the use of two parallel streams (rgb and depth), we used two GPUs during training for faster computation. So direct test on single GPU might be difficult.
If you wish to train on a single GPU, assuming you have sufficient memory, you could remove the `tf.device('/device:GPU:X')` scope variables in `global_agg_net.py` during training. 
Cheers!
