### ISSUE TITLE
Where i can find code to do inference and visualization outputs after calibration?

### ISSUE THREAD

**Issue by chowkamlee81** [epiception/CalibNet#3]
Hai,

Got only training code. But Where i can find code to do inference and visualization outputs after calibration?

Pls do the needful

**Comment by Ruijin1988** [comment]
yes, got the same need. wish it comes soon.

**Comment by epiception** [comment]
Hey guys,

Sorry for the delay on my part. Its been a little hard for me, cause I recently shifted to a new country for Grad School. No one else is supporting the repo right now, and due to the shift, I lost all access to computational resources. I'm actually in need of a good final set of weights which I could release as part of the final code. The weights can also be used for visualization (I have some code written with Open3D for colorized point clouds in python). 

Any help with training would be awesome, I'm looking for other options on here as well.

Thank you :)

**Comment by deeptf** [comment]
@epiception : Isn't there a pre-trained weights already included in this repository? Can't that be used to provide inference code? 
Would be really great if you can provide starter inference program.

If more stable weights are needed, can you please explain a bit more detailed what training parameters or dataset you need help to train? Thanks.

**Comment by deeptf** [comment]
@epiception : Any Update? 
Thanks!

**Comment by epiception** [comment]
@deeptf  Hey! The weights that are provided are for an old version. I wrote a new resnet-18 architecture for the camera ready, it's on the experimental branch. Unfortunately, the trained weights for those and the inference code aren't available, but its worth a checkout. The structure for training and evaluation is similar.
